server:
  port: 9000

spring:
  application:
    name: spotify-clone-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - Authorization
              - Content-Type
              - Accept
            allowCredentials: true

jwt:
  public-key-path: classpath:certs/public_key.der
